import type { OpenClawRoleMode } from "@/lib/openclaw/tools/types";

export const ROLE_ALLOWED_TOOLS: Record<OpenClawRoleMode, string[]> = {
  campaign_launcher: [
    "create_campaign",
    "update_campaign",
    "list_campaigns",
    "get_campaign",
    "archive_campaign",
    "create_funnel",
    "update_funnel",
    "add_funnel_step",
    "update_funnel_step",
    "reorder_funnel_steps",
    "list_funnels",
    "get_funnel",
    "publish_funnel",
    "select_landing_variant",
    "upsert_landing_variant",
    "activate_email_sequence",
    "create_content_asset",
    "update_content_asset",
    "change_content_status",
    "list_content_assets",
    "create_email_template",
    "update_email_template",
    "create_email_sequence",
    "add_email_sequence_step",
    "enroll_lead_in_sequence",
    "create_tracking_link",
    "log_analytics_event",
    "create_agent_run",
    "append_agent_run_log",
    "complete_agent_run",
    "fail_agent_run",
    "get_pending_approvals",
    "create_approval_item",
    "decide_approval",
    "get_org_settings",
  ],
  offer_analyst: [
    "list_campaigns",
    "get_campaign",
    "get_campaign_metrics",
    "log_analytics_event",
  ],
  content_strategist: [
    "create_content_asset",
    "update_content_asset",
    "change_content_status",
    "list_content_assets",
    "create_email_template",
    "update_email_template",
    "create_tracking_link",
    "get_org_settings",
    "get_pending_approvals",
    "create_approval_item",
    "decide_approval",
  ],
  funnel_architect: [
    "create_funnel",
    "update_funnel",
    "add_funnel_step",
    "update_funnel_step",
    "reorder_funnel_steps",
    "list_funnels",
    "get_funnel",
    "publish_funnel",
    "select_landing_variant",
    "upsert_landing_variant",
    "get_campaign",
    "list_campaigns",
    "get_pending_approvals",
    "create_approval_item",
    "decide_approval",
  ],
  lead_nurture_worker: [
    "create_lead",
    "update_lead_status",
    "update_lead_score",
    "list_leads",
    "enroll_lead_in_sequence",
    "activate_email_sequence",
    "queue_test_email",
    "get_org_settings",
    "get_pending_approvals",
    "create_approval_item",
    "decide_approval",
  ],
  analyst: [
    "list_campaigns",
    "get_campaign",
    "list_content_assets",
    "get_campaign_metrics",
    "log_analytics_event",
  ],
  analyst_worker: [
    "list_campaigns",
    "get_campaign",
    "list_content_assets",
    "get_campaign_metrics",
    "log_analytics_event",
  ],
  supervisor: ["*"],
};

export function isToolAllowedForRole(roleMode: OpenClawRoleMode, toolName: string) {
  const allowed = ROLE_ALLOWED_TOOLS[roleMode] ?? [];
  if (allowed.includes("*")) return true;
  return allowed.includes(toolName);
}

