import { redirect } from "next/navigation";

import { ReportsClient } from "@/app/admin/reports/ReportsClient";
import { getCurrentOrgIdFromCookie } from "@/lib/cookies";

export default async function AdminReportsPage() {
  const orgId = await getCurrentOrgIdFromCookie();
  if (!orgId) redirect("/admin/onboarding");

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Weekly Reports</h1>
        <p className="text-sm text-muted-foreground">
          Weekly summaries generated by the Reports Analyst worker (generation + delivery automation coming next).
        </p>
      </div>
      <ReportsClient organizationId={orgId} />
    </div>
  );
}

