begin;

-- Scheduled/stub-published social content generated by Auto Mode.
create table if not exists public.content_posts (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  campaign_id uuid references public.campaigns(id) on delete set null,
  platform text not null, -- tiktok | youtube_shorts
  title text not null,
  script text not null,
  caption text not null,
  cta_link text,
  status text not null default 'draft', -- draft | scheduled | posted | failed
  scheduled_at timestamptz,
  posted_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists content_posts_org_status_idx on public.content_posts(organization_id, status, scheduled_at asc);
create index if not exists content_posts_campaign_idx on public.content_posts(campaign_id, created_at desc);

alter table public.jobs
  add column if not exists processed_at timestamptz;

alter table public.content_posts enable row level security;

drop policy if exists content_posts_select_member on public.content_posts;
create policy content_posts_select_member on public.content_posts
  for select using (public.is_org_member(organization_id));

drop policy if exists content_posts_mutate_operator on public.content_posts;
create policy content_posts_mutate_operator on public.content_posts
  for all using (public.is_org_operator(organization_id))
  with check (public.is_org_operator(organization_id));

commit;

